server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 192.168.1.127
      database: spitdb
  redis:
    host: 192.168.1.127

jwt:
  config:
    # 加盐
    key: lmzw
    ttl: 3600000
