server: 
  port: 9004
spring: 
  application:  
    name: tensquare-article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.127:3306/tensquare_article?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
#    hibernate:
      # 更新或者创建数据表结构
#      ddl-auto: update
  redis:
    host: 192.168.1.127

  data:
    mongodb:
      host: 192.168.1.127
      database: recruitdb

jwt:
  config:
    # 加盐
    key: lmzw
    ttl: 3600000

eureka:
  client:
    serviceUrl:
     defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true    # 确保模块之间能够跨域访问

